version: "3.8"
services:
    villabe:
        build:
            context: ./aesthetic-villa-be
        ports:
            - "5909:5909"
        networks:
            - villabe-network
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        depends_on:
            - villabe
        environment:     # Add environment variables here
            SERVER_URL: http://villabe:5909
        networks:
            - villabe-network

networks:
  villabe-network: 
    driver: bridge